---
-
  name: "configure | Manage prosody.cfg.lua"
  become: true
  ansible.builtin.template:
    backup: true
    src: "prosody.cfg.lua.j2"
    dest: "{{ prosody_config_dir }}/ansible-managed.cfg.lua"
    owner: "root"
    group: "{{ prosody_group }}"
    mode: "0640"
  notify:
    - "Validate prosody config"
    - "Validate prosody certs"
    - "Restart prosody"
