---

-
  name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  tags: ["prosody", "prosody-install", "prosody-ssl", "prosody-configure", "prosody-service"]

-
  include_tasks: "install-{{ ansible_os_family }}.yml"
  when: "prosody_install"
  tags: ["prosody", "prosody-install"]

-
  import_tasks: "ssl.yml"
  when: "prosody_ssl"
  tags: ["prosody", "prosody-ssl"]

-
  import_tasks: "configure.yml"
  when: "prosody_configure"
  tags: ["prosody", "prosody-configure"]

-
  import_tasks: "service.yml"
  when: "prosody_service"
  tags: ["prosody", "prosody-service"]
