---
- # This include ensures this role is only used against supported hosts
  name: "Include OS-specific variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags: ["prosody", "prosody-install", "prosody-ssl", "prosody-configure", "prosody-service"]
-
  name: "Include install.yml"
  when: "prosody_install"
  ansible.builtin.import_tasks: "install.yml"
  tags: ["prosody", "prosody-install"]
-
  name: "Include ssl.yml"
  when: "prosody_ssl"
  ansible.builtin.import_tasks: "ssl.yml"
  tags: ["prosody", "prosody-ssl"]
-
  name: "Include configure.yml"
  when: "prosody_configure"
  ansible.builtin.import_tasks: "configure.yml"
  tags: ["prosody", "prosody-configure"]
-
  name: "Include service.yml"
  when: "prosody_service"
  ansible.builtin.import_tasks: "service.yml"
  tags: ["prosody", "prosody-service"]
