---

-
  name: "Manage prosody service"
  become: true
  service:
    name: "prosody"
    state: "{{ prosody_service_state }}"
    enabled: "{{ prosody_service_enabled }}"

-
  name: "Wait for prosody to start"
  wait_for:
    port: 5222
