---
-
  name: "ssl | Ensure the SSL directory exists"
  when: "prosody_ssl_pairs | length > 0"
  become: true
  ansible.builtin.file:
    state: "directory"
    path: "{{ prosody_ssl_dir }}"
    owner: "{{ prosody_owner }}"
    group: "{{ prosody_group }}"
    mode: "0700"
-
  name: "ssl | Manage the SSL keys"
  when: "prosody_ssl_pairs | length > 0"
  become: true
  no_log: true
  with_items: "{{ prosody_ssl_pairs }}"
  ansible.builtin.copy:
    content: "{{ item.key }}"
    dest: "{{ prosody_ssl_dir }}/{{ item.name }}.key"
    owner: "{{ prosody_owner }}"
    group: "{{ prosody_group }}"
    mode: "0600"
  notify:
    - "Validate prosody certs"
    - "Restart prosody"
-
  name: "ssl | Manage the SSL certificates"
  when: "prosody_ssl_pairs | length > 0"
  become: true
  no_log: true
  with_items: "{{ prosody_ssl_pairs }}"
  ansible.builtin.copy:
    content: "{{ item.crt }}"
    dest: "{{ prosody_ssl_dir }}/{{ item.name }}.crt"
    owner: "{{ prosody_owner }}"
    group: "{{ prosody_group }}"
    mode: "0600"
  notify:
    - "Validate prosody certs"
    - "Restart prosody"
