---
- name: "Converge"
  hosts: "all"
  tasks:
    - name: "Include cornfeedhobo.prosody"
      ansible.builtin.include_role:
        name: "cornfeedhobo.prosody"
      vars:
        prosody_install: true
        prosody_configure: true
        prosody_config:
          modules_enabled:
            - "tls"
        prosody_vhosts:
          example.org: |
            Component "muc.example.org" "muc"
              name = "example.org chatrooms"
              modules_enabled = { "muc_mam", "vcard_muc" }
